from pathlib import Path

PROJECT_ROOT = Path(__file__).parent
ASSETS_DIR = PROJECT_ROOT / "assets"

FPS = 60
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
TITLE = "The Last Samurai"
BG_COLOR = (0, 0, 0)

PLAYER_SPEED = 5
GRAVITY = 0.8
